version: 0.0
os: linux
files:
  - source: /
    destination: /opt/deployin-node-application/my-node-app
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu

