# version: 0.0
# os: linux
# files:
#   - source: /
#     destination: /opt/deployin-node-application/my-node-app
# hooks:
#   AfterInstall:
#     - location: scripts/install_dependencies.sh
#       timeout: 300
#       runas: ubuntu
#   ApplicationStart:
#     - location: scripts/start_server.sh
#       timeout: 300
#       runas: ubuntu

version: 0.0
os: linux
files:
  - source: /
    # destination: /opt/deployin-node-application/my-node-
    destination: /opt/NodeJSapplications/my-node-app
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root

